closes #25

diff --git a/bin/bootstrap-and-run-agent b/bin/bootstrap-and-run-agent
--- a/bin/bootstrap-and-run-agent
+++ b/bin/bootstrap-and-run-agent
@@ -72,19 +72,26 @@ fi
 
 # create a fresh virtualenv. we use and older 1.9.x version of 
 # virtualenv as this seems to work more reliable than newer versions.
-CURL_CMD="curl -OL --insecure -s https://raw.github.com/pypa/virtualenv/1.9.X/virtualenv.py"
+CURL_CMD="curl -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz"
 echo ""
 echo "################################################################################"
-echo "## Downloading virtualenv"
+echo "## Downloading and installing virtualenv"
 echo "## CMDLINE: $CURL_CMD"
-$CURL_CMD
+curl -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz
 OUT=$?
 if [ $OUT -ne 0 ];then
    echo "Couldn't download virtuelenv via curl! ABORTING"
    exit 1
 fi
 
-BOOTSTRAP_CMD="$PYTHON virtualenv.py --unzip-setuptools --python=$PYTHON $R_SYS_DIR"
+tar xvfz virtualenv-1.9.tar.gz
+OUT=$?
+if [ $OUT -ne 0 ];then
+   echo "Couldn't unpack virtualenv! ABORTING"
+   exit 1
+fi
+
+BOOTSTRAP_CMD="$PYTHON virtualenv-1.9/virtualenv.py --python=$PYTHON $R_SYS_DIR"
 echo ""
 echo "################################################################################"
 echo "## Creating virtualenv"
@@ -96,7 +103,20 @@ if [ $OUT -ne 0 ];then
    exit 1
 fi
 
+# active the virtualenv
 source $R_SYS_DIR/bin/activate
+
+UPDATE_SETUPTOOLS_CMD="pip install --upgrade setuptools"
+echo ""
+echo "################################################################################"
+echo "## Updating virtualenv"
+echo "## CMDLINE: $UPDATE_SETUPTOOLS_CMD"
+$UPDATE_SETUPTOOLS_CMD
+OUT=$?
+if [ $OUT -ne 0 ];then
+   echo "Couldn't update virtualenv! ABORTING"
+   exit 1
+fi
 
 # for now we use development version directly from git
 # this blows up the virtualenv (and agent bootstrap time) significantly
