update reqs on create_ve script; check errors

diff --git a/bin/radicalpilot-create-static-ve b/bin/radicalpilot-create-static-ve
--- a/bin/radicalpilot-create-static-ve
+++ b/bin/radicalpilot-create-static-ve
@@ -2,8 +2,8 @@
 
 scriptname="radical-pilot-create-static-ve"
 
-reqs="pymongo==2.8 python-hostlist netifaces setproctitle ntplib pyzmq"
-reqs="$reqs apache-libcloud colorama backports.ssl-match-hostname"
+reqs="pymongo==2.8 python-hostlist netifaces==0.10.4 setproctitle ntplib pyzmq"
+reqs="$reqs apache-libcloud colorama backports.ssl-match-hostname orte_cffi msgpack-python"
 
 setuptools="setuptools==0.6c11"
 pip="pip==1.4.1"
@@ -71,9 +71,9 @@ mkdir -p "$prefix/rp_install"
 
 virtualenv "$prefix"
 .          "$prefix"/bin/activate
-pip install --upgrade $setuptools
-pip install --upgrade $pip
-pip install --upgrade $reqs
+pip install --upgrade $setuptools || echo 'pip failed (ST)'  && exit
+pip install --upgrade $pip        || echo 'pip failed (PIP)' && exit
+pip install --upgrade $reqs       || echo 'pip failed (req)' && exit
 
 # install the radical stack (utils, saga, pilot) into a separate tree
 # ($prefix/rp_install(, so that any local install can use the ve *w/o* 
@@ -98,9 +98,10 @@ echo 'import pkg_resources'                       >> $ru_ns_init
 echo 'pkg_resources.declare_namespace (__name__)' >> $ru_ns_init
 echo                                              >> $ru_ns_init
 
-pip install --install-option="--prefix=$prefix/rp_install" radical.utils
-pip install --install-option="--prefix=$prefix/rp_install" saga-python
-pip install --install-option="--prefix=$prefix/rp_install" radical.pilot
+PIP_INSTALL="pip install --install-option='--prefix=$prefix/rp_install'"
+$PIP_INSTALL radical.utils || echo 'pip failed (RU)' && exit
+$PIP_INSTALL saga-python   || echo 'pip failed (RS)' && exit
+$PIP_INSTALL radical.pilot || echo 'pip failed (RP)' && exit
 
 OLD_SAGA_VERBOSE=$SAGA_VERBOSE
 OLD_RADICAL_VERBOSE=$RADICAL_VERBOSE
