merge from devel

diff --git a/bin/radicalpilot-create-static-ve b/bin/radicalpilot-create-static-ve
--- a/bin/radicalpilot-create-static-ve
+++ b/bin/radicalpilot-create-static-ve
@@ -1,28 +1,58 @@
-scriptname="radicalpilot-create-static-ve"
+#!/bin/sh
 
-# set -x
+scriptname="radical-pilot-create-static-ve"
 
-# sanity checks
-if test "`basename -- $0`" = "$scriptname"
-then
-    echo "This script is meant to be sourced, not executed (to retain any virtualenv etc.)."
-    exit
-fi
+reqs="pymongo==2.8 python-hostlist netifaces setproctitle ntplib pyzmq"
+reqs="$reqs apache-libcloud colorama backports.ssl-match-hostname"
 
+setuptools="setuptools==0.6c11"
+pip="pip==1.4.1"
+
+# ------------------------------------------------------------------------------
+#
+help(){
+
+    err="$1"
+    ret=0
+    
+    if ! test -z "$err"
+    then
+        ret=1
+        printf "\n    ERROR: $err\n"
+    fi
+
+    cat <<EOT
+
+    usage: $0 <target> [-h]
+
+    This script creates a virtualenv at the given target location.  That
+    virtualenv should be suitable to be used as static VE for a radical.pilot
+    target resource, and can be specified in a resource configuration for RP.
+
+EOT
+    exit $ret
+}
+
+
+# ------------------------------------------------------------------------------
+#
 prefix=$1
+
+if test "$prefix" = "-h"
+then
+    help 
+fi
 
 if test -z "$prefix"
 then
-    printf "\n\tusage: radicalpilot-create-static-ve <target>\n\n"
-    return
+    help "missing target"
 fi
 
 # We don't want to overwrite VE's -- the hack to get the namespace import in
 # place is too invasive to be applied to an existing VE.
 if test -e "$prefix"
 then
-    echo "error: target '$prefix' exists"
-    return
+    help "target '$prefix' exists"
 fi
 
 # Ensure we install in an absolute path -- pip seems to like that better...
@@ -40,18 +70,17 @@ mkdir -p "$prefix"
 mkdir -p "$prefix/rp_install"
 
 virtualenv "$prefix"
-source "$prefix"/bin/activate
-pip install --upgrade setuptools==0.6c11
-pip install --upgrade pip==1.4.1
-pip install --upgrade colorama python-hostlist pymongo==2.8 apache-libcloud
+.          "$prefix"/bin/activate
+pip install --upgrade $setuptools
+pip install --upgrade $pip
+pip install --upgrade $reqs
 
 # install the radical stack (utils, saga, pilot) into a separate tree
 # ($prefix/rp_install(, so that any local install can use the ve *w/o* 
 # the radical stack, by re-routing PYTHONPATH
 python_version=`python -c 'import distutils.sysconfig as sc; print sc.get_python_version()'`
-ve_mod_prefix=`python -c 'import distutils.sysconfig as sc; print sc.get_python_lib()'`
-rp_mod_prefix=`echo $ve_mod_prefix | sed -e "s|$prefix|$prefix/rp_install|"`
-
+ve_mod_prefix=` python -c 'import distutils.sysconfig as sc; print sc.get_python_lib()'`
+rp_mod_prefix=`echo $ve_mod_prefix | sed -e "s|$prefix|$prefix/rp_install/|"`
 
 PYTHONPATH="$rp_mod_prefix:$PYTHONPATH"
 export PYTHONPATH
@@ -69,8 +98,8 @@ echo 'import pkg_resources'                       >> $ru_ns_init
 echo 'pkg_resources.declare_namespace (__name__)' >> $ru_ns_init
 echo                                              >> $ru_ns_init
 
-# pip install --install-option="--prefix=$prefix/rp_install" radical.utils
-# pip install --install-option="--prefix=$prefix/rp_install" saga-python
+pip install --install-option="--prefix=$prefix/rp_install" radical.utils
+pip install --install-option="--prefix=$prefix/rp_install" saga-python
 pip install --install-option="--prefix=$prefix/rp_install" radical.pilot
 
 OLD_SAGA_VERBOSE=$SAGA_VERBOSE
